#!/usr/bin/env python3
"""Wrap the Metal sharpening shader in bgfx's shader container.

bgfx loads shaders from a small binary container: a text-parsed header (magic,
varying hashes, uniform records) followed by the shader source and a NUL. On
Metal the stored bytes are MSL *source*, which renderer_mtl.cpp hands to
newLibraryWithSource once at program creation — there is no compiled metallib
anywhere in this pipeline.

shaderc would produce the same bytes, but building it drags in Dawn and the
rest of its toolchain (BGFX_BUILD_TOOLS is off in this tree). The container is
small and fully specified by ShaderMtl::create in renderer_mtl.cpp, so this
script emits it directly. Run it after editing code/fs_sharpen.metal:

    python3 tools/make_fs_sharpen_bin.py

The layout it writes, matching the parser field for field:

    uint32  magic           'F','S','H', BGFX_SHADER_BIN_VERSION (11)
    uint32  hashIn          varying hash; must equal the vertex shader's hashOut
    uint32  hashOut         0 (fragment shaders publish no varying hash)
    uint16  numUniforms     uniform records follow
    per record:
        uint8   nameLen     name bytes, no terminator
        uint8   type        UniformType | 0x10 (fragment bit) | 0x20 (sampler bit)
        uint8   num
        uint16  regIndex
        uint16  regCount
        uint16  texInfo
        uint16  texFormat
    uint32  shaderSize      byte length of the source
    bytes   source          MSL text
    uint8   0               terminator the parser skips

The three s_tex records are byte-identical to the ones in bgfx's
fs_ocornut_imgui_mtl blob, which is what makes bgfx::setTexture(0, s_tex, ...)
bind this shader's texture and sampler arguments the same way.
"""

import re
import struct
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SOURCE = ROOT / "code" / "fs_sharpen.metal"
HEADER = ROOT / "code" / "fs_sharpen.bin.h"

BGFX_SHADER_BIN_VERSION = 11
UNIFORM_FRAGMENT_BIT = 0x10
UNIFORM_SAMPLER_BIT = 0x20
UNIFORM_TYPE = {"sampler": 0, "end": 1, "vec4": 2, "mat3": 3, "mat4": 4}

# Same varying hash fs_ocornut_imgui publishes: the vertex shader's outputs do not
# change, so the fragment shader consuming them carries the identical input hash.
VARYING_HASH_IN = 0xE1F28301

# (name, type byte, num, regIndex, regCount, texInfo, texFormat)
S_TEX_RECORDS = [
    ("s_texSampler", UNIFORM_TYPE["end"] | UNIFORM_FRAGMENT_BIT, 1, 0xFFFF, 1, 0, 0),
    ("s_texTexture", UNIFORM_TYPE["end"] | UNIFORM_FRAGMENT_BIT, 1, 0xFFFF, 1, 0, 0),
    ("s_tex", UNIFORM_TYPE["sampler"] | UNIFORM_FRAGMENT_BIT, 0, 0, 0, 0, 0),
]
U_SHARPNESS_RECORD = ("u_sharpness", UNIFORM_TYPE["vec4"] | UNIFORM_FRAGMENT_BIT, 1, 0, 1, 0, 0)


def build_blob(msl: bytes) -> bytes:
    out = bytearray()
    out += struct.pack("<I", (ord("F") | (ord("S") << 8) | (ord("H") << 16) | (BGFX_SHADER_BIN_VERSION << 24)))
    out += struct.pack("<I", VARYING_HASH_IN)
    out += struct.pack("<I", 0)

    records = S_TEX_RECORDS + [U_SHARPNESS_RECORD]
    out += struct.pack("<H", len(records))
    for name, utype, num, regindex, regcount, texinfo, texformat in records:
        raw = name.encode("ascii")
        out += struct.pack("<B", len(raw))
        out += raw
        out += struct.pack("<BBHHHH", utype, num, regindex, regcount, texinfo, texformat)

    out += struct.pack("<I", len(msl))
    out += msl
    out += b"\x00"
    return bytes(out)


def parse_like_bgfx(blob: bytes) -> None:
    """Decode the blob exactly the way ShaderMtl::create does, as a self-check."""
    off = 0
    magic, hash_in, hash_out = struct.unpack_from("<III", blob, off)
    off += 12
    if (magic & 0xFFFFFF) != (ord("F") | (ord("S") << 8) | (ord("H") << 16)):
        raise SystemExit(f"bad magic {magic:08x}")
    count = struct.unpack_from("<H", blob, off)[0]
    off += 2
    for _ in range(count):
        name_len = blob[off]
        off += 1
        name = blob[off:off + name_len].decode()
        off += name_len
        utype, num, regindex, regcount, texinfo, texformat = struct.unpack_from("<BBHHHH", blob, off)
        off += 10
        print(f"  uniform {name!r} type=0x{utype:02x} num={num} regIndex={regindex} regCount={regcount}")
    size = struct.unpack_from("<I", blob, off)[0]
    off += 4
    code = blob[off:off + size + 1]
    if len(code) != size + 1 or code[-1] != 0:
        raise SystemExit("code section does not match shaderSize")
    if len(blob) < off + size + 1:
        raise SystemExit("blob truncated")
    print(f"  shaderSize={size} hashIn={hash_in:08x} hashOut={hash_out:08x} total={len(blob)}")


def emit_header(blob: bytes) -> str:
    lines = [
        "// Generated by tools/make_fs_sharpen_bin.py from code/fs_sharpen.metal.",
        "// bgfx shader container, Metal variant (MSL source compiled at runtime).",
        "// Do not edit by hand; edit the .metal and re-run the script.",
        f"static const uint8_t fs_sharpen_mtl[{len(blob)}] =",
        "{",
    ]
    for i in range(0, len(blob), 16):
        chunk = blob[i:i + 16]
        hexes = ", ".join(f"0x{b:02x}" for b in chunk)
        comment = "".join(chr(b) if 32 <= b < 127 else "." for b in chunk)
        lines.append(f"\t{hexes},{'' if i + 16 >= len(blob) else ''} // {comment}")
    lines.append("};")
    lines.append("")
    return "\n".join(lines)


def main() -> None:
    msl = SOURCE.read_bytes()
    blob = build_blob(msl)
    print("self-check (ShaderMtl::create parse):")
    parse_like_bgfx(blob)
    HEADER.write_text(emit_header(blob))
    print(f"wrote {HEADER} ({len(blob)} bytes of blob)")


if __name__ == "__main__":
    sys.exit(main())
